### PR TITLE
Fix uploader spec expectations on order.

### PR DESCRIPTION
**Pull request by mtpereira**
The order the files are returned by Uploader#files is actually
irrelevant, so we should not have any expectations on that. This was
causing ./spec/uploader_spec.rb:41 (Triboelectric::Uploader#files with
a list should eq) to fail.

To remove any expectations on the results' order, we're now sorting both
the output and the spec expectation on the Uploader specs.

### CODE REVIEW

**Review by costis — COMMENTED** [review]
Instead of sorting maybe you would like to use the following:

https://relishapp.com/rspec/rspec-expectations/v/2-0/docs/matchers/include-matcher

**Review by robinbortlik — APPROVED** [review]
@mtpereira I would use https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/contain-exactly-matcher

But logic is right, so LGTM

**Comment by mtpereira** [comment]
@costis I've checked that but I decided against it because I do want to check that the elements are only the ones listed on the expectations. With `include`, it will pass even if there are extra elements on the result, whilst with `eq` that is not the case. Is there some sort of "exclusively include" check?

**Comment by mtpereira** [comment]
@robinbortlik That's it! I'll try that.

**Pull request merged**
