### PR TITLE
Adds a middleware that can be used in conjunction with rails

### PR DESCRIPTION
**Pull request by errm**

### CODE REVIEW

**Comment by mtpereira** [comment]
Still work in progress.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by errm** [comment]
@mtpereira do you still need this or can we close?

**Comment by mtpereira** [comment]
Hey @errm !

We need it, but we don't know when we're getting back to it. I say close it and we'll resume it later if needed.

Thanks!

**Comment by errm** [comment]
Ok no problem, the code will still be on the branch if needed

**Pull request closed without merging**
